modLoader = "javafml"
loaderVersion = "[34,)"
license = "GNU GPLv3"
[[mods]]
modId = "curiosquarkobp"
version = "${version}"
displayName = "Curios Quark Oddities Backpack"
issueTrackerURL = "https://github.com/yzl210/CuriosQuarkOBP/issues"
authors = "yzl210"
description = '''
Add curios support for quark oddities backpack
'''
[[dependencies.curiosquarkobp]]
modId = "quarkoddities"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.curiosquarkobp]]
modId = "curios"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

